# Generated by Django 6.0.1 on 2026-07-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
